// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type { GenericInsertOneOptions, IdOf } from '@/src/documents/index.js';

/**
 * ##### Overview
 *
 * The options for an `insertOne` command on a {@link Collection}.
 *
 * @example
 * ```ts
 * const result = await collection.insertOne({
 *   name: 'John',
 *   age: 30,
 * }, {
 *   timeout: 10000,
 * });
 * ```
 *
 * ---
 *
 * ##### Datatypes
 *
 * See {@link Collection}'s documentation for information on the available datatypes for collections.
 *
 * @see Collection.insertOne
 * @see CollectionInsertOneResult
 *
 * @public
 */
export type CollectionInsertOneOptions = GenericInsertOneOptions;

/**
 * ##### Overview
 *
 * Represents the result of an `insertOne` command on a {@link Collection}.
 *
 * @example
 * ```ts
 * const result = await collection.insertOne({
 *   name: 'John',
 *   age: 30,
 * });
 *
 * console.log(result.insertedId);
 * ```
 *
 * ---
 *
 * ##### The `_id` field
 *
 * The type of the `_id` field is inferred from the {@link Collection}'s type, if it is present.
 *
 * > **⚠️Warning:** It is the user's responsibility to ensure that the ID type accommodates all possible variations—including auto-generated IDs and any user-provided ones.
 *
 * If the collection is "untyped", or no `_id` field is present in its type, then it will default to {@link SomeId}, which is a union type covering all possible types for a document ID.
 *
 * You may mitigate this concern on untyped collections by using a type such as `{ _id: string } & SomeDoc` which would allow the collection to remain generally untyped while still statically enforcing the `_id` type.
 *
 * > **💡Tip:** See the {@link SomeId} type for more information, and concrete examples, on this subject.
 *
 * ---
 *
 * ##### The default ID
 *
 * By default, if no `_id` field is provided in the inserted document, it will be automatically generated and set as a string UUID (not an actual {@link UUID} type).
 *
 * You can modify this behavior by changing the {@link CollectionDefinition.defaultId} type when creating the collection; this allows it to generate a {@link UUID} or {@link ObjectId} instead of a string UUID.
 *
 * > **💡Tip:** See {@link SomeId} and {@link CollectionDefinition.defaultId} for more information, and concrete examples, on this subject.
 *
 * @see Collection.insertOne
 * @see CollectionInsertOneOptions
 *
 * @public
 */
export interface CollectionInsertOneResult<RSchema> {
  /**
   * The ID of the inserted document. This may have been autogenerated if no `_id` was present in the inserted document.
   *
   * See {@link CollectionInsertOneResult} for more information about the inserted id.
   */
  insertedId: IdOf<RSchema>,
}
