// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Internal
export interface InsertManyCommand {
  insertMany: {
    documents: object[];
    options?: InsertManyOptions;
  }
}

/**
 * Represents the options for the insertMany command.
 *
 * @field ordered - If true, when an insert fails, return without performing the remaining inserts.
 */
export interface InsertManyOptions {
  /**
   * If true, when an insert fails, return without performing the remaining inserts.
   *
   * If false, when an insert fails, continue with the remaining inserts if there are any.
   *
   * Defaults to true.
   * @default true
   */
  ordered?: boolean;
}

// Internal
export const insertManyOptionKeys = new Set(['ordered']);

/**
 * Represents the result of an insertMany command.
 *
 * @field acknowledged - If the operation was acknowledged.
 * @field insertedIds - The IDs of the inserted documents.
 * @field insertedCount - The number of inserted documents.
 */
export interface InsertManyResult {
  /**
   * True if the operation was acknowledged.
   */
  acknowledged: true;
  /**
   * The IDs of the inserted documents (including the autogenerated IDs).
   */
  insertedIds: string[];
  /**
   * The number of inserted documents (equals `insertedIds.length`).
   */
  insertedCount: number;
}
